name: Task Management System CI_CD

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build with Maven
        run: mvn clean package -DskipTests

  test:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run tests with Maven
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          JWT_LIFE: ${{ secrets.JWT_LIFE }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: mvn test

  deploy:
    runs-on: self-hosted
    needs: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build dockerfile
        run: docker build -t task-app-image .

      - name: Up docker-compose
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          JWT_LIFE: ${{ secrets.JWT_LIFE }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: docker compose up -d --force-recreate