name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-job:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t task-management-system .

  deploy-job:
    runs-on: self-hosted
    needs: build-job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy using Docker Compose
        run: |
          docker-compose up -d --force-recreate 
